version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      example-app-net:
        ipv4_address: 215.21.0.54

  app:
    build:
      context: .
    command:
      - /bin/bash
      - -c
      - |
        sh wait-rabbitmq.sh
        sh cmd-local.sh
    volumes:
      - ./src:/src # code
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    networks:
      example-app-net:
        ipv4_address: 215.21.0.100

      
  

networks:
  example-app-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 215.21.0.0/16
