version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - 5672:5672
      - 15672:15672

# ---- Application ----
  consumer:
    depends_on:
        - rabbitmq
    build: 
      context: ./consumer
    command:
      - /bin/bash
      - -c
      - |
        sh wait-rabbitmq.sh
        sh cmd-local.sh
    volumes:
      - ./consumer/src:/src # code
    ports:
      - 8000:8080
    

  publisher:
    depends_on:
        - consumer
    build: 
      context: ./publisher
    command:
      - /bin/bash
      - -c
      - |
        sh wait-rabbitmq.sh
        sh cmd-local.sh
    volumes:
      - ./publisher/src:/src # code
    ports:
      - 9000:8080
    