version: '3.8'

services:
  nats:
    image: nats
    ports:
      - 4222:4222
      - 8222:8222
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

# ---- Application ----

  app:
    build: 
      context: .
    depends_on:
      - nats
      - nats-1
      - nats-2
    command:
      - /bin/bash
      - -c
      - |
        sh cmd-local.sh
    volumes:
      - ./src:/src # code
    ports:
      - 8000:8080


networks:
  nats:
    name: nats