version: '3.8'

services:
  nats:
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: ["nats"]

  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

# ---- Application ----

  consumer:
    build: 
      context: ./consumer
    depends_on:
      - nats
      - nats-1
      - nats-2
    command:
      - /bin/bash
      - -c
      - |
        sh cmd-local.sh
    volumes:
      - ./consumer/src:/src # code
    ports:
      - 8000:8080
    # networks:
    #   - nats

  publisher:
    build: 
      context: ./publisher
    depends_on:
      - nats
      - nats-1
      - nats-2
      - consumer  
    command:
      - /bin/bash
      - -c
      - |
        sh cmd-local.sh
    volumes:
      - ./publisher/src:/src # code
    ports:
      - 9000:8080
    # networks:
    #   - nats

networks:
  nats:
    name: nats